### PR TITLE
Developed Chat Message Component

### PR DESCRIPTION
**Pull request by Lokeshranjan8**
Developed Chat Message Component

Summary of Changes:
- Implemented MainLayout component with necessary changes.
- Added Message component to handle chat messages.
- Fixed bugs related to message rendering.
- Refactored code for improved readability and maintainability.

### CODE REVIEW

**Comment by Sweetdevil144** [comment]
Screenshot 2024-06-04 at 6 36 51 PM

Correct the green column. Make sure to implement hooks properly. The message content should be sent only when I've send the `REQUEST`

**Comment by Lokeshranjan8** [comment]
msg111
is this column good?

**Comment by Sweetdevil144** [comment]
NO. See. I haven't typed anything yet I am able to see a tiny green box at right top corner of screen. Fix it to only be visible when something is present in input box.

**Review by Sweetdevil144 — APPROVED** [review]
LGTM!!

**Pull request merged**
